/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { MeshDistortMaterial, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Torus001: THREE.Mesh
    Torus003: THREE.Mesh
    Torus002: THREE.Mesh
  }
}

export function ReactLogo(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/react-logo.gltf') as GLTFResult
  const mesh = useRef<THREE.Group>(null)
  useFrame(() => {
    if (!mesh.current) return
    mesh.current.rotation.y += 0.005
    mesh.current.rotation.x -= 0.005
    mesh.current.rotation.z -= 0.005
  })

  return (
    <group {...props} dispose={null} ref={mesh} scale={1.7}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        position={[0, 0, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.27}
      >
        <meshStandardMaterial roughness={0} color='#1fb2f5' />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001.geometry}
          position={[0.34, -0.08, 0.02]}
          rotation={[-0.16, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        >
          <MeshDistortMaterial roughness={0} color='#1fb2f5' />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus003.geometry}
          position={[-0.04, -0.11, 0]}
          rotation={[0.89, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        >
          <MeshDistortMaterial roughness={0} color='#1fb2f5' />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus002.geometry}
          position={[-0.52, -0.1, 0.16]}
          rotation={[-1.18, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        >
          <MeshDistortMaterial roughness={0} color='#1fb2f5' />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/react-logo.gltf')
