/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Torus001: THREE.Mesh
    Torus003: THREE.Mesh
    Torus002: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
  }
}

export function ReactLogo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/react-logo.gltf') as GLTFResult
  return (
    <Float rotationIntensity={2}>
      <group {...props} dispose={null} scale={2} position={[1, -0.5, 0.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['default']}
          position={[0, 1.31, 0]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.27}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus001.geometry}
            material={materials['default']}
            position={[0.34, -0.08, 0.02]}
            rotation={[-0.16, 0, -Math.PI / 2]}
            scale={[3.75, 1.47, 3]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus003.geometry}
            material={materials['default']}
            position={[-0.04, -0.11, 0]}
            rotation={[0.89, 0, -Math.PI / 2]}
            scale={[3.75, 1.47, 3]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus002.geometry}
            material={materials['default']}
            position={[-0.52, -0.1, 0.16]}
            rotation={[-1.18, 0, -Math.PI / 2]}
            scale={[3.75, 1.47, 3]}
          />
        </mesh>
      </group>
    </Float>
  )
}

useGLTF.preload('/react-logo.gltf')
