/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { editable as e } from '@theatre/r3f'

type GLTFResult = GLTF & {
  nodes: {
    rocksA_forest: THREE.Mesh
  }
  materials: {
    ['Stone.007']: THREE.MeshStandardMaterial
  }
}

export function Stones(props: JSX.IntrinsicElements['group'] & { theatreKey: string }) {
  const { nodes, materials } = useGLTF('/stones.gltf') as GLTFResult
  return (
    <e.group {...props} dispose={null} theatreKey={props.theatreKey}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rocksA_forest.geometry}
        material={materials['Stone.007']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </e.group>
  )
}

useGLTF.preload('/stones.gltf')
