/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tree-spruce']: THREE.Mesh
  }
  materials: {
    color_main: THREE.MeshStandardMaterial
  }
}

export const Tree = (
  props: JSX.IntrinsicElements['group'] & { theatreKey: string },
) => {
  const { nodes, materials } = useGLTF('/models/tree.gltf') as GLTFResult
  return (
    <e.group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tree-spruce'].geometry}
        material={materials.color_main}
      />
    </e.group>
  )
}

useGLTF.preload('/models/tree.gltf')
